### PR TITLE
meson: Fix handling of the Python dependency

### LINKED ISSUE #3014: minimal multilib build fails
Building current `stable/v2.40` for Arch Linux multilib package (`lib32-util-linux`) fails.

```
[241/534] Compiling C object libmount/python/pylibmount.cpython-312-x86_64-linux-gnu.so.p/pylibmount.c.o
FAILED: libmount/python/pylibmount.cpython-312-x86_64-linux-gnu.so.p/pylibmount.c.o 
gcc -m32 -Ilibmount/python/pylibmount.cpython-312-x86_64-linux-gnu.so.p -Ilibmount/python -I../util-linux/libmount/python -Iinclude -I../util-linux/include -Ilibmount -I../util-linux/libmount -I/usr/include/python3.12 -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -D_GNU_SOURCE -include /build/lib32-util-linux/src/build/config.h -fno-common -Waddress-of-packed-member -Wdiscarded-qualifiers -Wformat-security -Wimplicit-function-declaration -Wmissing-declarations -Wmissing-parameter-type -Wmissing-prototypes -Wnested-externs -Wno-missing-field-initializers -Wold-style-definition -Wpointer-arith -Wredundant-decls -Wsign-compare -Wstrict-prototypes -Wtype-limits -Wuninitialized -Wunused-but-set-parameter -Wunused-but-set-variable -Wunused-parameter -Wunused-result -Wunused-variable -Wvla -Walloca -D_TIME_BITS=64 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/build/lib32-util-linux/src=/usr/src/debug/lib32-util-linux -flto=auto -fPIC -Wno-cast-function-type -Wno-error=redundant-decls -MD -MQ libmount/python/pylibmount.cpython-312-x86_64-linux-gnu.so.p/pylibmount.c.o -MF libmount/python/pylibmount.cpython-312-x86_64-linux-gnu.so.p/pylibmount.c.o.d -o libmount/python/pylibmount.cpython-312-x86_64-linux-gnu.so.p/pylibmount.c.o -c ../util-linux/libmount/python/pylibmount.c
In file included from /usr/include/python3.12/Python.h:38,
                 from ../util-linux/libmount/python/pylibmount.h:4,
                 from ../util-linux/libmount/python/pylibmount.c:21:
/usr/include/python3.12/pyport.h:586:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
  586 | #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
      |  ^~~~~
```

This was caused by commit 79546fc1b084839e635eba6736cd809bdbda5d6e, specifically dropping the code from `libmount/python/meson.build`. Adding these lines back makes the build succeed.

The build is very minimal, as I am interested in the libraries only. Please see the [PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/lib32-util-linux/-/blob/main/PKGBUILD) for the build options used.

### PR DESCRIPTION
**Pull request by jwillikers**
This PR fixes a couple of issues with the current Python handling in Meson.

1. I inadvertently rendered the `build-python` option useless in commit b6799cc. This caused issue #3014.
2. The `embed` argument for the Python dependency used to incorporate the `Python.h` header file worked around an issue in Meson itself, see https://github.com/mesonbuild/meson/issues/12862 and the discussion in #2924. Meson should actually require the `Python.h` header file be present when `find_installation` is called for the Python module. This has an additional side-effect that Meson 1.4.1 will require `Python.h` in order to run the tests which use `find_installation`. The tests just need the path to the Python executable, not the `Python.h` header file.

This PR fixes these problems by making sure to use the `build-python` option to determine whether or not to build `pylibmount`. It fixes the check for `Python.h` by checking for it explicitly when building `pylibmount` when using versions of Meson prior to 1.4.1. Finally, the Python module and `find_installation` are only used for `pylibmount` and `find_program` is used to incorporate the Python path for tests to ensure that the `Python.h` header file is not unnecessarily required for tests when using Meson version 1.4.1 or later.

Fixes #3014

### CODE REVIEW

**Comment by jwillikers** [comment]
> Well, the commits do not apply to `stable/2.40` branch... But at least I can confirm that building `master` with these on top works as expected. Thanks!

@eworm-de Thanks for checking! I'll cherry-pick these commits to `stable/v2.40` after they are merged.

**Comment by karelzak** [comment]
For `stable/2.40`, we need a separate PR :-)

**Comment by jwillikers** [comment]
> For `stable/2.40`, we need a separate PR :-)

Yep, I'll do that!
