### ISSUE TITLE
libblkid: 2.41: static library libblkid.a interferes with libudev.a

### ISSUE THREAD

**Issue by fjaell** [util-linux/util-linux#3626]
while trying to build a static lvm with util-linux 2.41.1 I get several errors like the following:

`    [CC] lvm.static `                                                   
` /usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/14.3.0/../../../../lib/libudev.a(util.o): in function split:
(.text+0x8d0): multiple definition of split; /usr/lib/gcc/x86_64-pc-linux-gnu/14.3.0/../../../../lib/libblkid.a(strutils.c.o):(.text+0x1e80): first defined here `

util-linux 2.41.1 was build with meson on a up-to-date CRUX 3.8 system. It works with 2.40.4 without errors. 
The same applies to a static build of cryptsetup.

**Comment by karelzak** [comment]
I have created a PR to fix it.

BTW, we had a discussion about it on the mailing list:
https://lore.kernel.org/util-linux/hjy6pccal442gk26tgjkol43aoicvkak4p2wy64ouk2ksfdhjb@7a2yap2jorf4/

The best is to add `ul_` prefix to all generic functions. Another way is to add the ul_ prefix everywhere when generating a static library.

Note that static libraries and binaries are generally undesirable for almost all use cases.

**Comment by fjaell** [comment]
Many thanks for the quick fix! 
We are providing static versions of binaries only if they are usable within a initrd, like lvm or cryptsetup for example.

**Comment by fjaell** [comment]
I've tested your patch, it applies, but I see two other collisions with udev:

- the functions split and strappend in strutils.c

Note: I don't see these problems with util-linux 2.40.4 and older?

**Comment by karelzak** [comment]
> I've tested your patch, it applies, but I see two other collisions with udev:
> 
>     * the functions split and strappend in strutils.c

Should be fixed in the PR.

> Note: I don't see these problems with util-linux 2.40.4 and older?

Yes, lib/env.c uses strv.h since v2.41.
