### ISSUE TITLE
minimal multilib build fails

### ISSUE THREAD

**Issue by eworm-de** [util-linux/util-linux#3014]
Building current `stable/v2.40` for Arch Linux multilib package (`lib32-util-linux`) fails.

```
[241/534] Compiling C object libmount/python/pylibmount.cpython-312-x86_64-linux-gnu.so.p/pylibmount.c.o
FAILED: libmount/python/pylibmount.cpython-312-x86_64-linux-gnu.so.p/pylibmount.c.o 
gcc -m32 -Ilibmount/python/pylibmount.cpython-312-x86_64-linux-gnu.so.p -Ilibmount/python -I../util-linux/libmount/python -Iinclude -I../util-linux/include -Ilibmount -I../util-linux/libmount -I/usr/include/python3.12 -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -D_GNU_SOURCE -include /build/lib32-util-linux/src/build/config.h -fno-common -Waddress-of-packed-member -Wdiscarded-qualifiers -Wformat-security -Wimplicit-function-declaration -Wmissing-declarations -Wmissing-parameter-type -Wmissing-prototypes -Wnested-externs -Wno-missing-field-initializers -Wold-style-definition -Wpointer-arith -Wredundant-decls -Wsign-compare -Wstrict-prototypes -Wtype-limits -Wuninitialized -Wunused-but-set-parameter -Wunused-but-set-variable -Wunused-parameter -Wunused-result -Wunused-variable -Wvla -Walloca -D_TIME_BITS=64 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/build/lib32-util-linux/src=/usr/src/debug/lib32-util-linux -flto=auto -fPIC -Wno-cast-function-type -Wno-error=redundant-decls -MD -MQ libmount/python/pylibmount.cpython-312-x86_64-linux-gnu.so.p/pylibmount.c.o -MF libmount/python/pylibmount.cpython-312-x86_64-linux-gnu.so.p/pylibmount.c.o.d -o libmount/python/pylibmount.cpython-312-x86_64-linux-gnu.so.p/pylibmount.c.o -c ../util-linux/libmount/python/pylibmount.c
In file included from /usr/include/python3.12/Python.h:38,
                 from ../util-linux/libmount/python/pylibmount.h:4,
                 from ../util-linux/libmount/python/pylibmount.c:21:
/usr/include/python3.12/pyport.h:586:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
  586 | #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
      |  ^~~~~
```

This was caused by commit 79546fc1b084839e635eba6736cd809bdbda5d6e, specifically dropping the code from `libmount/python/meson.build`. Adding these lines back makes the build succeed.

The build is very minimal, as I am interested in the libraries only. Please see the [PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/lib32-util-linux/-/blob/main/PKGBUILD) for the build options used.

**Comment by eworm-de** [comment]
Just added that code back in to make the package build:
https://gitlab.archlinux.org/archlinux/packaging/packages/lib32-util-linux/-/commit/9e6f38ae0fad5dbbf0ade158ada45591251db55e

Though wondering... Why is that python code building at all? It is disabled... No?

**Comment by eworm-de** [comment]
CC @jwillikers for authorship of causing commit

**Comment by jwillikers** [comment]
@eworm-de Thanks for the CC. I'm trying to figure out exactly what's going on in your situation. I have the feeling that adding that code back disabled building `pylibmount`. Is that the case?

**Comment by jwillikers** [comment]
@eworm-de Assuming that this is indeed the case, then I think that PR #3020 should fix your issue. If you can confirm that it fixes this, that would be great.

**Comment by eworm-de** [comment]
Answered in PR #3020 ...
