### ISSUE TITLE
Fails to build with glibc 2.28 and linux headers 6.1

### ISSUE THREAD

**Issue by nolange** [util-linux/util-linux#2448]
Hello,

I cant compile util-linux 2.39.2, the relevant details are:

1. glibc header `<sys/stat.h>` does not have the member `statx.stx_mnt_id`
2. linux header `<linux/stat.h>` has the member `statx.stx_mnt_id`.
    (configure will however **not define** `HAVE_LINUX_STAT_H`)
3. configure has the lines:
    ```
    ac_fn_c_check_type "$LINENO" "struct statx" "ac_cv_type_struct_statx" "#include <linux/stat.h>
    ac_fn_c_check_member "$LINENO" "struct statx" "stx_mnt_id" "ac_cv_member_struct_statx_stx_mnt_id" "#include <linux/stat.h>
    ```

Which means `HAVE_STRUCT_STATX_STX_MNT_ID` will be defined, based on `<linux/stat.h>`, but later `<sys/stat.h>` is used. The result is that the build fails:

```
../libmount/src/hook_mount.c: In function 'hook_create_mount':
../libmount/src/hook_mount.c:301:47: error: 'STATX_MNT_ID' undeclared (first use in this function); did you mean 'STATX_UID'?
  301 |   rc = statx(api->fd_tree, "", AT_EMPTY_PATH, STATX_MNT_ID, &st);
      |                                               ^~~~~~~~~~~~
      |                                               STATX_UID
../libmount/src/hook_mount.c:301:47: note: each undeclared identifier is reported only once for each function it appears in
../libmount/src/hook_mount.c:302:26: error: 'struct statx' has no member named 'stx_mnt_id'; did you mean 'stx_uid'?
  302 |   cxt->fs->id = (int) st.stx_mnt_id;
      |                          ^~~~~~~~~~
      |                          stx_uid
```

As workaround, I patched the lines in the configure script to use `<sys/stat.h>`, but I am pretty sure thats a horrible hack.

**Comment by mator** [comment]
what is your linux distribution? thanks

**Comment by nolange** [comment]
> what is your linux distribution? thanks

A custom crosstools-ng toolchain.

**Comment by karelzak** [comment]
It's fragile to check for sys/stat.h and use linux/stat.h. I'll prepare a PR for this.
