### ISSUE TITLE
[v2.41] undefined reference to `add_namespace_for_nsfd'

### ISSUE THREAD

**Issue by ThomasDevoogdt** [util-linux/util-linux#3483]
I get this error when building with buildroot using util-linux v2.41.

```
sys-utils/lsns-lsns.o: In function `read_process':
lsns.c:(.text+0x9e8): undefined reference to `add_namespace_for_nsfd'
collect2: error: ld returned 1 exit status
```

It seems that `add_namespace_for_nsfd` is only compiled if `USE_NS_GET_API`, but it's also used in `add_namespace_from_sock` and, `read_opened_namespaces` without checking if `USE_NS_GET_API` has been set. This compile issue is most probably introduced by commit https://github.com/util-linux/util-linux/commit/3c6adc940f902072c02f8df2457e23ba3ca56acc.
