### ISSUE TITLE
macOS build issues for `mkswap` and `hardlink`

### ISSUE THREAD

**Issue by cho-m** [util-linux/util-linux#1432]
Related Homebrew PR https://github.com/Homebrew/homebrew-core/pull/83809 I am working on.

---

First, it looks like macOS build starting failing on v2.37.1+ for `mkswap`. It still builds on v2.37, so some change in-between those releases.

Specifically, in `mkswap.c`, there is an include chain where `c.h` includes `<grp.h>`, which has following code in macOS SDK:
```h
#if (!defined(_POSIX_C_SOURCE) && !defined(_XOPEN_SOURCE)) || defined(_DARWIN_C_SOURCE)
#include <uuid/uuid.h>
__BEGIN_DECLS
char *group_from_gid(gid_t, int);
struct group *getgruuid(uuid_t);
int getgruuid_r(uuid_t, struct group *, char *, size_t, struct group **);
__END_DECLS
#endif
```

This then picks up Apple's `uuid.h`, defines `_UUID_UUID_H`, prevents including util-linux's `uuid.h`, and finally causes build error due to not having all needed macros.
```
error: use of undeclared identifier 'UUID_STR_LEN'.
```

I was able to get past this by including `<uuid.h>` before `c.h` (or any other header with include chain) in `mkswap.c`; however, I don't know if this is best way to deal with.

---

The second issue is building `hardlink`. In Homebrew, this has been disabled due to problems building, which I have diagnosed to be due to Apple's `<sys/xattr.h>` not having all needed functions.

I wasn't able to find a way to force disable this header from being detected without deleting the corresponding `AC_CHECK_HEADERS` in `configure`.

I am not familiar enough with autotools to comment on this, but it would be nice to automatically disable the header and/or corresponding code if functions like `lgetxattr` are not found. Otherwise, an option to force this off.

**Comment by karelzak** [comment]
> we could probably set `--disable-ipcrm --disable-ipcs` as defaults on macos ?!

OK, `darwin` excluded for IPCs

Thanks for your help guys!
